### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [HanxunHuangLemonBear/Active-Passive-Losses#4]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by HanxunH** [comment]
Hi,

1. It should be able to work on tabular data. There is no constraint on the types of input data it works on. 
2. We did not test such an idea. But you may start by looking into the loss values for individual samples. Higher values may reflect that they could be potentially noisy.

**Comment by nazaretl** [comment]
I see, thank you! Last question: your code is not tailored to the few datasets you test, right? It seems that only dataset.py contains special datasets and hard-coded parameters.

**Comment by HanxunH** [comment]
There are some hard-coded parameters in the dataset.py for asymmetrical noise. For noise generations on your dataset, you may need to change them.

**Comment by nazaretl** [comment]
thank you!
